[package]
name = "rmrs"
version = "0.1.0"
authors = ["Christian Steimel <me@C14L.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
rocket_contrib = "0.4.0"
rocket_cors = "0.5.0-beta-1"
serde = { version = "1.0", features = ["derive"] }

